# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               savokiss.me
tagline:             'flying get√'
description:         'flying get√ 总是要拼了命继续努力'
url:                 http://jaynaruto.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              savokiss
  url:               https://twitter.com/savokiss
  email:             jaynaruto@qq.com

# Custom vars
version:             1.0.0

# Comments
comments :
    provider : duoshuo
    duoshuo :
          short_name : savoki

